-- Migration 011: Import Goldin Institute team members
-- Executed: Feb 7, 2026
-- Source: GATHER_Team_Import_Template.xlsx
-- Note: Already executed against live DB. This file is the repo record.

INSERT INTO team_members (email, first_name, last_name, title, role, phone, bio, photo_url, linkedin_url, alternate_emails, fellowships) VALUES
  ('travis@goldininstitute.org', 'Travis', 'Rejman', 'Executive Director', 'super_admin', '3129511691', 'Travis Rejman is the founding Executive Director of the Goldin Institute, a global non-profit based in Chicago that has inspired, equipped and connected grassroots leaders in over 50 countries over the last twenty years. Prior to working with Diane Goldin to create and launch the Goldin Institute in 2002, Travis served as Director for the Council for a Parliament of the World''s Religions, leading the development of the international program for the 2004 Parliament of the World''s Religions and launching the Partner Cities Network. Most recently, Travis has been focused on supporting the Goldin Global Fellows and the Chicago Peace Fellows programs and refining the GATHER platform to support communities of practice as they learn and work together to tackle tough issues across boundaries. Travis has worked on the ground with community leaders in Asia, Europe, Africa, the Middle-East and South and North America.', 'https://goldininstitute.org/wp-content/uploads/2023/01/Travis-Rejman-PP-02-1024x1024.jpg.avif', 'https://www.linkedin.com/in/travisrejman/', ARRAY['gather@goldininstitute.org'], NULL),
  ('stobertg@gmail.com', 'Tyler', 'Stober', 'GATHER UX Designer', 'team', '351 933 394 313', NULL, NULL, NULL, ARRAY['tyler@goldininstitute.org'], NULL),
  ('yusuph@goldininstitute.org', 'Yusuph', 'Masanja', 'Director, Dar es Salaam Peace Fellows', 'team', '255 2226664449', 'Yusuph Masanja is a 2018 Goldin Global Fellow Alumni from Tanzania and the Director of the Goldin Institute''s Tanzania office. In addition to hosting the Dar es Salaam Peace Fellows program, Yusuph works with the Goldin Institute team to coordinate the Global Alumni Network spanning over 55 countries.', 'https://goldininstitute.org/wp-content/uploads/2022/08/Yusuph-Masanja-Profile-1.png.avif', NULL, '{}'::text[], '[{"program": "GGF", "year": 2018}]'::jsonb),
  ('lissette@goldininstitute.org', 'Lissette', 'Mateus Roa', 'Director, Bogota Peace Fellows', 'team', '57 (315) 876-5443', 'Lissette Mateus Roa studied Primary Education at the faculty of Humanities at the National Pedagogical University of Colombia. Lissette continued her studies in English for two years in England. Lissette has extensive experience in family empowerment and the prevention of domestic violence, sexual abuse and child abuse. Lissette is an Alumni of the Goldin Global Fellows and lead facilitator of the "Pedagogy of Care and Reconciliation" that helps former youth combatants in the civil wars in Uganda and Colombia reintegrate back into their communities.', 'https://goldininstitute.org/wp-content/uploads/2022/08/Lissette-Square2-1024x1024.jpg.avif', NULL, '{}'::text[], '[{"program": "GGF", "year": 2018}]'::jsonb),
  ('jassi@goldininstitute.org', 'Jassi', 'Sandhar', 'Director, Storytelling and Community Engagement', 'team', '44 7951 565534', 'Jassi earned her PhD in International Law at the University of Bristol (UK) in 2021, where she explored the role of girl child soldiers in conflict (focusing on the Sri Lankan and Ugandan wars). Her areas of interest are gender and war, feminist legal theory, critical race theory, children in armed conflict, and self-determination and civil resistance struggles.', 'https://goldininstitute.org/wp-content/uploads/2023/01/Jassi-Sandhar-PP.jpg.avif', NULL, '{}'::text[], NULL),
  ('grese@goldininstitute.org', 'Grese', 'Sermaxhaj', 'Communications Associate', 'team', '383 49 722 994', 'Grese Sermaxhaj is a graduate with Honors from the University of Prishtina, Kosovo, in the Department of Political Science with background in public relations and communications. She is a 2023 Goldin Global Fellow (English). Grese works as a Communications Associate at the Goldin Institute, highlighting international fellows through interviews, feature stories, and crafting social media content.', 'https://goldininstitute.org/wp-content/uploads/2023/12/Grese-Sermaxhaj-PP4.jpg.avif', NULL, '{}'::text[], '[{"program": "GGF", "year": 2023}]'::jsonb),
  ('john@goldininstitute.org', 'John', 'Zeigler', 'Senior Director of Programs', 'team', '312-315-4988', 'John Zeigler Jr. is Senior Director of Programs, guiding the connections between the Chicago and Global teams of the Goldin Institute in addition to his role as Director of the Egan Office of Urban Education and Community Partnerships (UECP) and adjunct faculty at DePaul University.', 'https://goldininstitute.org/wp-content/uploads/2022/09/John-Zeigler-PP-2022.jpeg.avif', NULL, '{}'::text[], NULL),
  ('oz@goldininstitute.org', 'Oz', 'Ozburn', 'Senior Director of Design', 'team', '(540) 272-5245', 'Oz Ozburn brings her planning and design skills to support all aspects of the work of the Goldin Institute. As an architect, Oz is experienced in deep listening and research to uncover opportunities to solve tough challenges through thoughtful design and skillful implementation.', 'https://goldininstitute.org/wp-content/uploads/2023/08/Oz-Ozburn-PP.jpg.avif', NULL, '{}'::text[], NULL),
  ('michael@goldininstitute.org', 'Michael', 'Henderson', 'Director, Chicago Peace Fellows', 'team', '(567) 288-9741', 'Michael Henderson serves as the director of the Mutual Aid Collaborative, a joint initiative of the Alumni of the Chicago Peace Fellows program. A strong believer in the power of positive influence, Michael is a hands-on coach who invests his time and resources in his client''s dreams and goals.', 'https://goldininstitute.org/wp-content/uploads/2022/09/Henderson-Michael-PP.jpg.avif', NULL, '{}'::text[], NULL),
  ('zeki@goldininstitute.org', 'Zeki', 'Salah', 'Communications Associate', 'team', '(504) 481-1233', 'Zeki Salah joined the Goldin Institute in 2021 and works primarily with the Chicago Peace Fellows as a storyteller, communicator, and facilitator. He is passionate about bottom-up grassroots change and has documented many of the Peace Fellows'' projects and collaborations as articles on the Goldin Institute''s website.', 'https://goldininstitute.org/wp-content/uploads/2023/12/Zeki-Salah.jpg', NULL, '{}'::text[], NULL),
  ('dorcas@goldininstitute.org', 'Dorcas', 'Kiplagat', NULL, 'team', '254 722 703 787', 'Dr. Dorcas Kiplagat is a community development practitioner and education professional who works with grassroots communities across Africa and globally. She holds a Ph.D. in Education from the Catholic University of Eastern Africa and remains deeply committed to locally driven solutions that promote education, dignity, resilience, and hope within communities.', 'https://goldininstitute.org/wp-content/uploads/2026/01/Dorcas-Kiplagat-PP-1024x1024.png', NULL, '{}'::text[], '[{"program": "GGF", "year": 2011}]'::jsonb);
